### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by FredHappyface** [FredHappyface/Android.EweSticker#3]
See below for a list of things in the pipeline:

- [x] Version 2021.06.12
  - [x] Screenshots
  - [x] Version 2021.06.12+ changelog 
  - [x] Add to Google Play
  - [x] Add to F-droid (in progress)
- [x] Next Version 
  - [x] App Tutorial (Online) 
  - [x] Ignore the compat sticker when creating groups 
  - [x] Add recently used (most recent 30)
  - [x] SVG back arrow icon 
  - [x] Add actions, options and about headings
  - [x] Test
